[package]
name = "prime-search"
version = "0.1.0"
authors = ["prime <prime@kmc.gr.jp>"]
edition = "2018"

[dependencies]
iron = "0.6"
router = "0.6"
mount = "0.4"
staticfile = "0.5.0"
urlencoded = "0.6.0"
lazy_static = "1.4.0"
